### PR TITLE
home page branch merge request

### PR DESCRIPTION
**Pull request by Mikearaya**
#### - different kind of hover reposes depending on the element posion

# Status: Requested :eyes:

### CODE REVIEW

**Comment by SofiBretz** [comment]
### Changes required ♻️
### Hello @Mikearaya! 🌟

Great work on this project, but you need to fix the issues below before moving on ⬇️

- [x] Consider making the width of the main page as the original page and center the body:


Original:


- [ ] On the 'navbar' The first eight elements should be links (to other sections or #) ([link](https://web.archive.org/web/20140301004610/http://www.apple.com/) to page), consider fix this.

- [ ] On the 'bottom' It contains four elements which are links (to other articles or `#`) ([link to page](https://web.archive.org/web/20140301004610/http://www.apple.com/))

- [ ] On the 'footer' consider add the links on this part as the original page:


Original:


- [x] Consider adding the 'demo' link to your readme file.

- [x] Make sure that basic CSS bad practices are not used ([article for support ](https://speckyboy.com/good-bad-css-practices)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)

* no repeating of the same rule. For example the colors:
Screenshot from 2020-04-03 18-14-56

_**After making the required changes please submit a new code review request**_
Good luck! 🍀 You are almost there! 💪

SofiBretz.

**Comment by Mikearaya** [comment]
Thank you for your feedback I have managed to make the changes requested. below are the changes I have applied since my last code review request based on the response I have received.

- centered content of the page giving it equal space on both sides. the main reason i made it fit the whole screen with was I read it from Microverse curriculum project-specific requirement 

Microverse Main Curriculum

- changed all the pseudo links with anchor tag inside HTML file

** I have added a link to the live demo but it's on the `home-page-brach` branch and maybe you have missed it**
Mikearaya apple-clone at home-page-branch

##  kindly review the changes I made, so I can merge and proceed to my next task if everything is in place. Thank you :eyes: :man_office_worker:

**Review by christianotieno — CHANGES_REQUESTED** [review]
# **CHANGES REQUIRED** :warning:
Hey @Mikearaya  :wave:
-
You have done a splendid job! :tada: 
- While it may be infuriatingly frustrating to progress with a project due to lots of required review changes, it is always a plus to welcome the review process as a learning opportunity. The aim is to always make you a better professional wholistically.

- We are all here for each other's success and positive progress. That said, we still do have some few changes to carry out with this project before we proceed (see review comment).

##
### Everything is shaping up good. There are some minor issues that need to be tweaked for our page to shape up fully.
- Your website has a scroll (shouldn't be there) and the navbar looks a bit misplaced. At the bottom, the image links appear also not to be in place as is seen from the original website. 
- This is what we have so far
apple_clone

- Let's improve it to match the original site
apple
 
- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding 💯 
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

**Comment by Mikearaya** [comment]
- edited navbar and bottom alignment to match the original page.

#### thank you for pointing out the imperfection on my last request. :smiley: 

about the scroll bar, the original page has a scroll bar too unless you view it while the browser window is zoomed out below 70% in which case the clone also doesn't have a scroll bar too.

**Review by christianotieno — COMMENTED** [review]
## Pull Request under review by Christian Otieno (TSE)

**Review by christianotieno — APPROVED** [review]
# PROJECT APPROVED 🍾 

***All the required minimum changes have been made in this project. I will go ahead and mark this as complete.*** 
- Congratulations on the splendid job @Mikearaya! 👍  
- You can now merge to master. I wish the very best in your next tasks 🥇 
##

Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

**Comment by Mikearaya** [comment]
Thank you for your time and review @SofiBretz  and @christianotieno

**Pull request merged**
